### ISSUE TITLE
Account for `string` in Create parameters

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/airdrops#1]
Related https://github.com/sablier-labs/v2-core/issues/1086

**Comment by smol-ninja** [comment]
@razgraf for the campaigns, what shape name should be used? When a user claims, it would make call to create functions. Should we use `""` i.e. blank or do we want to use a custom name (may be campaign name) or do we want to specify shape name when creating a campaign?

**Comment by smol-ninja** [comment]
Sounds good.

**Comment by razgraf** [comment]
> specify shape name when creating a campaign which means storing it as an immutable parameter and then use it in claim flow

This sounds good to me!

**Comment by smol-ninja** [comment]
Question: Since `shape` is redundant in `MerkleInstant`, it makes sense to pass it as a separate parameter for Merkle LL and LT instead of `ConstructorParams`. But that would add lot more code the contracts that anticipated. Would it be OK to ignore `shape` in `MerkleInstant` for this release? This will let me include `shape` in `ConstructorParams`.

Note: In the future, a good approach would be to have a shared constructor parameter between `createMerkleLL` and `createMerkleLT` and a separate for `createMerkleInstant`. A lot of parameters are common between LL and LT but unfortunately due to the same `ConstructorParams` across all create functions, we cannot DRY'ify the code between LL and LT.

RFC @sablier-labs/solidity

**Comment by PaulRBerg** [comment]
It should be fine to ignore `shape` in `MerkleInstant` in the next release.

I also agree that we should have separate constructor parameters for `createMerkleInstant`.
