### ISSUE TITLE
Add Murky as dev dependency

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/airdrops#10]
To avoid having to maintain the code + benefit from the latest updates in Murky.

https://github.com/sablier-labs/airdrops/pull/5#discussion_r1850989530

**Comment by andreivladbrg** [comment]
I was trying to do this, but I’m afraid we can’t achieve it using `bun`, as the repo does not have a `package.json` file (https://app.warp.dev/block/pTzN20g0PhTxXTb9GGRFQn). Also, there’s an issue that has been open for 3 months now (https://github.com/dmfxyz/murky/issues/20) with no response from the maintainer.

However, it worked using `yarn`: https://app.warp.dev/block/IibDd7etEkOYmYtVHVeu66.

So, should we wait until a `package.json` file is added to the repo, or should we discard this change?

**Comment by PaulRBerg** [comment]
Will disregard for now. Thanks for trying to add it as a dependency.

Please add a comment in their repo to ask them to add a `package.json` file.

**Comment by PaulRBerg** [comment]
Reopening as they added `package.json`

https://github.com/dmfxyz/murky/pull/23#event-15441186546
