### ISSUE TITLE
Change the amount based variables in `MerkleLL.Schedule` to percentages

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/airdrops#27]
### Problem

When an airdrop campaign is created, it is very likely that not everyone will receive the same amount airdropped.

Which means we can have:
- A gets 100K
- B gets 10K
- C gets 10

The issue arises because the new unlock amounts variable stored in the `Schedule` struct is globally set for each stream.

https://github.com/sablier-labs/airdrops/blob/aa45dabb6c82c7cbf7ad02411e143bbe206f4a26/src/SablierMerkleLL.sol#L53-L54

https://github.com/sablier-labs/airdrops/blob/aa45dabb6c82c7cbf7ad02411e143bbe206f4a26/src/types/DataTypes.sol#L48-L54

This can result in situations where a creator wants to set a cliff amount of 1000 for A but only 1 for C, which is problematic. Furthermore, if the cliff amount exceeds the minimum amount airdropped, the stream cannot be created.

### Solution

The solution is to use percentage-based variables in the Schedule struct instead of amount-based ones, similar to how [TrancheWithPercentage](https://github.com/sablier-labs/airdrops/blob/aa45dabb6c82c7cbf7ad02411e143bbe206f4a26/src/types/DataTypes.sol#L64C12-L64C33) works.

---

Credits to @razgraf for this finding.

**Comment by smol-ninja** [comment]
Will the new struct look like the following?

```solidity
struct Schedule {
    uint40 startTime;
    UD2x18 startPct;
    uint40 cliffDuration;
    UD2x18 cliffPct;
    uint40 totalDuration;
}
```

**Comment by andreivladbrg** [comment]
> Will the new struct look like the following?

yes, which is great as we will have only one slot 🤌👨‍🍳


64 * 2 + 40 * 3 = 248 < 256
