### ISSUE TITLE
Create a separate repo for Airdrops

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/airdrops#4]
<sup>Originally discussed in https://github.com/sablier-labs/v2-core/discussions/1068</sup>

Make a separate repo for Airdrops and move Merkle lockup contracts along with their test suites in the new repo.

**Comment by PaulRBerg** [comment]
Why create a `main` and a `staging` branch for this repo?

Why not just `main`? We have a clean slate here.

**Comment by smol-ninja** [comment]
Its just `main`. `staging` is only to review PR. Have a look https://github.com/sablier-labs/airdrops/pull/5.
